config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # TODO need admin to see this routes
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'videos#index'

  resources :videos, only: %w[index show] do
    member do
      put :vote
    end
  end

  resources :users do
    member do
      get :share_movie
      post :share
      get :video
      get :subscribers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id                   :bigint           not null, primary key
#  comment              :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  reference_comment_id :integer
#  user_id              :integer
#  video_id             :integer
#
# Indexes
#
#  index_comments_on_reference_comment_id  (reference_comment_id)
#  index_comments_on_user_id               (user_id)
#  index_comments_on_video_id              (video_id)
#
class Comment < ActiveRecord::Base
  belongs_to :video
  belongs_to :user
  belongs_to :reference_comment, foreign_key: :reference_comment_id, class_name: 'Comment'
end

app/models/set_builder.rb
class SetBuilder
  def initialize
    @set = []
  end

  attr_reader :set

  def show_set
    set
  end

  def add(number)
    if (validate_new_element(number))
      @set << number
      @set
    else
      puts 'Elements in set must unique'
    end
  end

  def remove(number)
    @set.reject!{|a| a == number }
    set
  end

  def check_exist(number)
    @set.include?(number)
  end

  private

  def validate_new_element(number)
    return false if check_exist(number)
    true
  end
end

app/models/test.rb
class Test

  def initialize

  end

  def reverse_array(array)
    swap(array, 0, array.size - 1)
    array
  end

  private

  def swap(array, head, tail)
    if head < tail
      temp = array[head]
      array[head] = array[tail]
      array[tail] = temp

      swap(array, head + 1, tail - 1)
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  user_code              :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :videos, foreign_key: :upload_user_id
  has_many :user_subscribes
  has_many :comments
  has_many :user_videos
  has_many :favorites_videos, through: :user_videos, source: :video
end

app/models/user_subscribe.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: user_subscribes
#
#  id               :bigint           not null, primary key
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  subcribe_user_id :integer
#  user_id          :integer
#
# Indexes
#
#  index_user_subscribes_on_subcribe_user_id  (subcribe_user_id)
#  index_user_subscribes_on_user_id           (user_id)
#
class UserSubscribe < ActiveRecord::Base
  belongs_to :subcribe_user, foreign_key: :subcribe_user_id, class_name: 'User'
  belongs_to :user
end

app/models/user_video.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: user_videos
#
#  id         :bigint           not null, primary key
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  video_id   :integer
#
# Indexes
#
#  index_user_videos_on_status    (status)
#  index_user_videos_on_user_id   (user_id)
#  index_user_videos_on_video_id  (video_id)
#
class UserVideo < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
end

app/models/user_vote_video.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: user_vote_videos
#
#  id         :bigint           not null, primary key
#  direction  :integer          default("no_react")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  video_id   :integer
#
# Indexes
#
#  index_user_vote_videos_on_direction  (direction)
#  index_user_vote_videos_on_user_id    (user_id)
#  index_user_vote_videos_on_video_id   (video_id)
#
class UserVoteVideo < ActiveRecord::Base
  belongs_to :user
  belongs_to :video

  enum direction: { no_react: 0, up_vote: 1, down_vote: 2 }
end

app/models/video.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: videos
#
#  id             :bigint           not null, primary key
#  description    :string
#  meta_data      :jsonb
#  platform       :integer          default("youtube")
#  status         :integer          default("processing")
#  thumbnail      :string
#  title          :string
#  total_dislikes :integer          default(0)
#  total_likes    :integer          default(0)
#  total_view     :integer          default(0)
#  video_url      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  upload_user_id :integer
#
# Indexes
#
#  index_videos_on_meta_data       (meta_data) USING gin
#  index_videos_on_upload_user_id  (upload_user_id)
#
class Video < ActiveRecord::Base
  belongs_to :user, foreign_key: :upload_user_id
  has_many :user_videos
  has_many :user_vote_videos

  validates :video_url, :title, :description, :platform, presence: true
  validate :validate_video_url

  enum status: { processing: 0, completed: 1, failed: 2 }
  enum platform: { youtube: 0, tiktok: 1, mannual_upload: 2 }

  scope :active_video, -> { completed }

  delegate :email,
           to: :user,
           allow_nil: true,
           prefix: true

  def self.detect_platform(url)
    return :youtube if url =~ /youtube|youtu/
    return :tiktok if url =~ /tiktok/

    nil
  end

  def validate_video_url
    url_pattern = /^(http|https):\/\/www.[youtube|youtu|tiktok]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?$/
    return if video_url =~ url_pattern

    errors.add(:video_url, 'does not support')
  end

  def user_vote_info(user)
    user_vote_videos.find_by(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  PER_PAGE_PAGING = 50
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :user

  def share_movie; end

  def share
    cmd_share = Users::Video::Share.call(user: current_user, params: params)
    if cmd_share.success?
      flash.now[:success] = 'Share video successfully!'
      redirect_to root_path
    else
      flash.now[:alert] = cmd_share.errors.full_messages.to_sentence
      render :share_movie
    end
  end

  private

  def user
    @user ||= current_user
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  before_action :set_video

  def index
    new_feed_cmd = Videos::GetAll.call(user: current_user, filter_params: params)

    unless new_feed_cmd.success?
      @videos = []
      return
    end

    @videos = new_feed_cmd.result
    @videos = @videos.includes(:user).page(params[:page]).per(PER_PAGE_PAGING)
  end

  def show
    redirect_to root_path unless @video
  end

  def vote
    cmd_vote = Users::Video::Vote.call(user: current_user, video: @video, direction: params[:direction])

    unless cmd_vote.success?
      respond_to do |format|
        format.js { render json: { error: 'You must login to vote' }, status: 500 }
      end
      return
    end

    respond_to do |format|
      format.js { render json: { success: true }, status: 200 }
    end
  end

  private

  def set_video
    @video = Video.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_message.html.haml
- if flash.present?
  .flash-message{ class: (flash[:error] || flash[:alert]) ? 'flash-error' :  'flash-success' }
    = flash[:error] || flash[:alert] || flash[:success] || flash[:notice]
    %span.close
      &times;

:javascript
  $('.flash-message .close').on('click', function(){
    $('.flash-message').fadeOut(600)
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FunnyMovies
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: 'all'
    = javascript_include_tag "application"
    %script{:async => "", :src => "https://www.tiktok.com/embed.js"}
  %body
    = render 'layouts/flash_message'
    #container-app
      .header
        %a.title{href: "#{root_path()}"}
          = image_tag 'home.png', class: 'home-icon'
          Funny Movies
        .login-bar
          - if current_user
            .user-container
              .user-info
                Welcome #{current_user.email}
              .share-movie
                = link_to 'Share a movie', share_movie_user_path(current_user) , class: 'btn btn-info'
              .logout
                = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-warning'
          - else
            .user-login-container
              = link_to 'Log In', new_user_session_path, class: 'btn btn-primary'
      .page-content
        = yield

app/views/users/share_movie.html.haml
.container#share-page
  .title
    Share a youtube/tiktok clip
  = form_for(@user, url: share_user_path(@user), method: :post, html: { class: 'form-vertical ' }) do |f|
    .row.share-table
      .form-group
        = f.label :youtube_url, class: 'col-md-3'
        = text_field_tag :video_url, '', class: 'form-control col-md-9'

      .form-group
        = f.label :title, class: 'col-md-3'
        = text_field_tag :title, '', class: 'form-control col-md-9'

      .form-group
        = f.label :description, class: 'col-md-3'
        = text_area_tag :description, '', class: 'form-control col-md-9'
    &nbsp
    &nbsp
    .row
      = f.submit 'Share', class: 'btn btn-primary share-button'

app/views/videos/_tiktok_iframe.html.haml
= @video.meta_data['input_html'].html_safe

app/views/videos/_youtube_iframe.html.haml
%iframe{:allow => "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "700", :src => @video.meta_data['embed_link'], :title => @video.title, :width => "700"}

app/views/videos/index.html.haml
.container#video-page
  .tab-bar
    %ul.nav
      %li.nav-item
        %a.nav-link{:href => "#{videos_path(type: 'trending')}", :class => "#{params[:type] == 'trending' ? 'active' : ''}"} Trending Video
      %li.nav-item
        %a.nav-link{:href => "#{videos_path(type: 'user')}", :class => "#{params[:type] == 'user' ? 'active' : ''}"} For You
      %li.nav-item
        %a.nav-link{:href => "#{videos_path(type: 'newest')}", :class => "#{params[:type] == 'newest' ? 'active' : ''}"} Newest
      %li.nav-item
        %a.nav-link{:href => "#{videos_path(type: 'all')}", :class => "#{params[:type] == 'all' ? 'active' : ''}"} All (For testing)
  .search-bar
  .container
    - @videos.each do |video|
      .video-item
        .video-iframe
          %a{href: "#{video_path(video)}"}
            = image_tag video.thumbnail || 'missing.jpg', class: 'video-thumbnail'
        .details
          .video-title
            = video.title
          .shared_by
            = "Shared by #{video.user_email}"
          .vote-info
            .like
              = video.total_likes
              = image_tag 'thumb-up.png', class: 'like-image like-button'
            .dislike
              .like
              = video.total_dislikes
              = image_tag 'thumb-down.png', class: 'like-image dislike-button'
          .description
            .title-desc Description
            .description-details
              = video.description

  .row
    .col
      .float-right
        = paginate @videos

app/views/videos/show.html.haml
.container#video-page
  .video-item.video-show-details
    - if @video.youtube?
      = render 'youtube_iframe', local: { video: @video }
    - elsif @video.tiktok?
      = render 'tiktok_iframe', local: { video: @video }
    - user_video = current_user ? @video.user_vote_info(current_user) : nil
    .details
      .video-title
        = @video.title
      .shared_by
        = "Shared by #{@video.user_email}"
      .vote-info
        .like
          .total-like-number
            = @video.total_likes
          = image_tag 'thumb-up.png', class: "like-image like-button #{user_video&.up_vote? ? 'active' : 'deactive'}"
        .dislike
          .like
            .total-dislike-number
              = @video.total_dislikes
            = image_tag 'thumb-down.png', class: "like-image dislike-button #{user_video&.down_vote? ? 'active' : 'deactive'}"
      .description
        .title-desc Description
        .description-details
          = @video.description
:javascript
  $(".like-button").on("click", function() {
    $.ajax({
      type: "PUT",
      url: "#{vote_video_path(@video)}",
      data: { direction: 1 },
      error: function(response) {
        if (response.status == 200) {
          $(".like-button").addClass("active")
          $(".like-button").removeClass("deactive")
          $(".dislike-button").addClass("deactive")
          $(".dislike-button").removeClass("active")

          var current_like = parseInt($('.total-like-number').text())
          var current_dislike = parseInt($('.total-dislike-number').text())
          $('.total-like-number').text(current_like + 1)
          if (current_dislike > 0) {
            $('.total-dislike-number').text(current_dislike - 1)
          }
        } else {
          alert("You must login to vote")
        }
      }
    });
  })

  $(".dislike-button").on("click", function() {
    $.ajax({
      type: "PUT",
      url: "#{vote_video_path(@video)}",
      data: { direction: 2 },
      error: function(response) {
        if (response.status == 200) {
          $(".dislike-button").addClass("active")
          $(".dislike-button").removeClass("deactive")
          $(".like-button").addClass("deactive")
          $(".like-button").removeClass("active")

          var current_like = parseInt($('.total-like-number').text())
          var current_dislike = parseInt($('.total-dislike-number').text())
          if (current_like > 0) {
            $('.total-like-number').text(current_like - 1)
          }
          $('.total-dislike-number').text(current_dislike + 1)
        } else {
          alert("You must login to vote")
        }
      }
    });
  })